[package]
name = "pbr_in_one_week"
version = "0.1.0"
authors = ["wengrs <flower_be_forever@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
